import { Router } from "express";
import authorize from "../middlewares/auth.middleware.js";
import {createSubscription, getUserSubscription} from "../controllers/subscription.controller.js";
const subscriptionRouter =Router();
subscriptionRouter.get("/",(req,res)=>res.send({title:"GET all users"}));
subscriptionRouter.get("/:id",(req,res)=>res.send({title:"get subscription"}));
subscriptionRouter.post("/",authorize,createSubscription);
subscriptionRouter.put("/:id",(req,res)=>res.send({title:"update the subscription"}));
subscriptionRouter.delete("/",(req,res)=>res.send({title:"delete subscription" }));
subscriptionRouter.get("/user/:id",authorize,getUserSubscription);
subscriptionRouter.put("/:id/cancel",(req,res)=>res.send({title:"cancel subscription"}));
subscriptionRouter.get("/upcoming-renewals",(req,res)=>res.send({title:"get upcoming renewals"}));
export default subscriptionRouter;